# Copyright © 2023 OpenIM open source community. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: OpenIM CI build android and ios sdk

on: 
  push:
    branches:
        - main
    paths-ignore:
        - "docs/**"
        - "README.md"
        - "README_zh-CN.md"
        - "CONTRIBUTING.md"
  pull_request:
    branches:
        - main
    paths-ignore:
        - "README.md"
        - "README_zh-CN.md"
        - "CONTRIBUTING.md"
        - "docs/**"

env:
  GO_VERSION: "1.19"
  GOLANGCI_VERSION: "v1.50.1"

jobs:
  android:
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
        contents: write
    environment:
      name: openim

    strategy:
      matrix:
        go_version: ["1.21"]
        # go_version: ["1.20","1.21"]
        os: [ubuntu-latest]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK and NDK
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          sdkmanager "ndk;21.4.7075529"

      - name: Install gomobile
        run: make install.gomobile

      - name: Initialize gomobile
        run: gomobile init

      - name: Build android sdk
        run: |
          make android
          echo "Run make android successfully" 
        continue-on-error: false

      # -H "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" \
      # "https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/io/mimo/open_im_sdk/v1.0.0/open_im_sdk-1.0.0.aar"
      - name: Upload to github package
        run: |
          curl -v -X PUT \
            -H "Authorization: Bearer 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" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@open_im_sdk.aar" \
            "https://maven.pkg.github.com/0xryanz/test/io/mimo/open_im_sdk/v1.0.1/open_im_sdk-1.0.1.aar"
    
  ios:
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
        contents: write

    environment:
      name: openim

    strategy:
      matrix:
        go_version: ["1.21"]
        os: [macos-latest]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install gomobile
        run: make install.gomobile

      - name: Initialize gomobile
        run: gomobile init

      - name: Set up Cocoapods
        run: gem install cocoapods

      - name: Build iOS Framework
        run: |
          make ios
          echo "Run make ios successfully" 

      # - name: Create Podspec file
      #   run: echo 'podspec content here' > MyFramework.podspec
      #
      # - name: Publish to Pod Registry
      #   run: |
      #     pod trunk register your@email.com
      #     pod trunk push MyFramework.podspec
